/* The following code was generated by JFlex 1.7.0 */

package lexical_analyzer;
import java.io.IOException;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>lexical_analyzer/Scanner.flex</tt>
 */
public class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\15\1\21\1\22\1\16\22\0\1\13\1\12\1\14"+
    "\2\12\1\37\1\44\1\11\1\27\1\30\1\36\1\35\1\34\1\17"+
    "\1\6\1\20\1\7\11\2\1\41\1\33\1\23\1\40\1\24\2\12"+
    "\32\1\1\31\1\12\1\32\1\43\1\5\1\12\1\46\1\61\1\53"+
    "\1\50\1\57\1\67\1\60\1\54\1\55\1\1\1\65\1\62\1\1"+
    "\1\47\1\51\1\70\1\1\1\52\1\64\1\56\1\66\1\4\1\71"+
    "\1\10\1\63\1\1\1\25\1\42\1\26\1\45\6\0\1\21\u1fa2\0"+
    "\1\21\1\21\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\3\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\15\2\1\0\1\2\5\0"+
    "\1\32\1\33\1\34\1\35\3\2\1\36\1\37\1\40"+
    "\4\2\1\41\13\2\1\42\1\43\1\3\1\44\1\45"+
    "\1\0\1\46\10\2\1\47\11\2\1\0\2\2\1\50"+
    "\2\2\1\51\1\2\1\52\1\53\7\2\1\0\1\54"+
    "\5\2\1\55\1\56\3\2\1\57\1\4\1\35\1\60"+
    "\3\2\1\61\3\2\1\62\1\63\2\2\1\64\1\65"+
    "\1\2\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\72\0\350\0\u0122\0\u015c"+
    "\0\u0196\0\u01d0\0\u020a\0\u0244\0\u027e\0\72\0\72\0\72"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\72\0\72"+
    "\0\72\0\u02b8\0\72\0\72\0\72\0\72\0\u02f2\0\u032c"+
    "\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc"+
    "\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692\0\u06cc"+
    "\0\u0706\0\u0740\0\72\0\72\0\72\0\72\0\u077a\0\u07b4"+
    "\0\u07ee\0\164\0\164\0\164\0\u0828\0\u0862\0\u089c\0\u08d6"+
    "\0\164\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c"+
    "\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u05e4\0\164\0\u0658\0\72"+
    "\0\72\0\u0b8e\0\164\0\u0bc8\0\u0c02\0\u0c3c\0\u0c76\0\u0cb0"+
    "\0\u0cea\0\u0d24\0\u0d5e\0\164\0\u0d98\0\u0dd2\0\u0e0c\0\u0e46"+
    "\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\u0fdc\0\u1016"+
    "\0\164\0\u1050\0\u108a\0\164\0\u10c4\0\164\0\164\0\u10fe"+
    "\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u125a\0\u1294\0\164"+
    "\0\u12ce\0\u1308\0\u1342\0\u137c\0\u13b6\0\164\0\164\0\u13f0"+
    "\0\u142a\0\u1464\0\164\0\u0b8e\0\164\0\164\0\u149e\0\u14d8"+
    "\0\u1512\0\164\0\u154c\0\u1586\0\u15c0\0\164\0\164\0\u15fa"+
    "\0\u1634\0\164\0\164\0\u166e\0\164";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\2\2\1\7\1\3"+
    "\1\10\1\2\1\5\1\11\2\5\1\12\1\13\1\2"+
    "\1\5\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\3\1\40\1\41"+
    "\1\42\1\43\1\3\1\44\1\45\1\46\1\3\1\47"+
    "\2\3\1\50\2\3\1\51\1\52\1\53\73\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\24\3\2\0\1\4"+
    "\3\0\1\54\1\4\63\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\1\55\23\3\2\0\1\4\3\0\1\54"+
    "\1\4\1\56\62\0\2\57\1\0\11\57\2\0\2\57"+
    "\2\0\47\57\14\60\2\0\54\60\17\0\1\61\72\0"+
    "\1\61\70\0\1\62\4\0\1\63\13\0\1\64\71\0"+
    "\1\65\71\0\1\66\32\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\1\3\1\67\2\3\1\70\11\3\1\71"+
    "\5\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\3\3\1\72\20\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\4\3\1\73\14\3\1\74\2\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\11\3\1\75"+
    "\12\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\3\3\1\76\2\3\1\77\15\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\1\3\1\100\17\3\1\101"+
    "\2\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\4\3\1\102\17\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\1\3\1\103\12\3\1\104\7\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\3\3\1\105"+
    "\1\106\4\3\1\107\12\3\1\0\2\3\1\0\2\3"+
    "\1\0\2\3\35\0\10\3\1\110\13\3\1\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\1\111\17\3\1\112"+
    "\3\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\4\3\1\113\17\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\6\3\1\114\15\3\2\0\1\115\4\0"+
    "\1\115\63\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\4\3\1\116\17\3\2\0\1\117\4\0\1\117\73\0"+
    "\1\120\60\0\14\60\1\121\1\0\54\60\15\61\2\5"+
    "\53\61\17\0\1\122\53\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\2\3\1\123\21\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\4\3\1\124\17\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\16\3\1\125"+
    "\5\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\1\126\7\3\1\127\13\3\1\0\2\3\1\0\2\3"+
    "\1\0\2\3\35\0\1\3\1\130\22\3\1\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\1\131\23\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\10\3\1\132"+
    "\13\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\20\3\1\133\3\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\2\3\1\134\21\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\16\3\1\135\5\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\3\3\1\136"+
    "\20\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\11\3\1\137\12\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\12\3\1\140\11\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\4\3\1\141\17\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\14\3\1\142"+
    "\7\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\1\3\1\143\22\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\3\3\1\144\20\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\7\3\1\145\14\3\15\122"+
    "\2\0\1\146\1\122\2\0\47\122\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\1\147\23\3\1\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\7\3\1\150\14\3"+
    "\1\0\2\3\1\0\2\3\1\0\2\3\35\0\14\3"+
    "\1\151\7\3\1\0\2\3\1\0\2\3\1\0\2\3"+
    "\35\0\20\3\1\152\3\3\1\0\2\3\1\0\2\3"+
    "\1\0\2\3\35\0\10\3\1\153\13\3\1\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\4\3\1\154\17\3"+
    "\1\0\2\3\1\0\2\3\1\0\2\3\35\0\11\3"+
    "\1\155\12\3\1\0\2\3\1\0\2\3\1\0\2\3"+
    "\35\0\11\3\1\156\12\3\1\0\2\3\1\0\2\3"+
    "\1\0\2\3\35\0\11\3\1\157\12\3\1\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\14\3\1\160\7\3"+
    "\1\0\2\3\1\0\2\3\1\0\2\3\35\0\1\161"+
    "\23\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\7\3\1\162\14\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\7\3\1\163\14\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\16\3\1\133\5\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\5\3\1\164"+
    "\16\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\5\3\1\165\16\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\14\3\1\166\7\3\15\122\2\0\1\167"+
    "\1\122\2\0\47\122\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\15\3\1\170\6\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\12\3\1\171\11\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\4\3\1\172"+
    "\17\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\7\3\1\173\14\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\12\3\1\174\11\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\11\3\1\175\12\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\17\3\1\176"+
    "\4\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\1\3\1\177\22\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\1\3\1\200\22\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\10\3\1\201\13\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\11\3\1\202"+
    "\12\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\11\3\1\203\12\3\15\122\2\0\1\167\1\122\2\0"+
    "\1\122\1\204\45\122\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\1\3\1\205\22\3\1\0\2\3\1\0"+
    "\2\3\1\0\2\3\35\0\1\3\1\206\22\3\1\0"+
    "\2\3\1\0\2\3\1\0\2\3\35\0\1\3\1\207"+
    "\22\3\1\0\2\3\1\0\2\3\1\0\2\3\35\0"+
    "\11\3\1\210\12\3\1\0\2\3\1\0\2\3\1\0"+
    "\2\3\35\0\1\211\23\3\1\0\2\3\1\0\2\3"+
    "\1\0\2\3\35\0\12\3\1\212\11\3\1\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\7\3\1\213\14\3"+
    "\1\0\2\3\1\0\2\3\1\0\2\3\35\0\2\3"+
    "\1\214\21\3\1\0\2\3\1\0\2\3\1\0\2\3"+
    "\35\0\20\3\1\215\3\3\1\0\2\3\1\0\2\3"+
    "\1\0\2\3\35\0\4\3\1\216\17\3\1\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\1\3\1\217\22\3"+
    "\1\0\2\3\1\0\2\3\1\0\2\3\35\0\3\3"+
    "\1\220\20\3\1\0\2\3\1\0\2\3\1\0\2\3"+
    "\35\0\20\3\1\221\3\3\1\0\2\3\1\0\2\3"+
    "\1\0\2\3\35\0\11\3\1\222\12\3\1\0\2\3"+
    "\1\0\2\3\1\0\2\3\35\0\1\3\1\223\22\3"+
    "\1\0\2\3\1\0\2\3\1\0\2\3\35\0\4\3"+
    "\1\224\17\3\1\0\2\3\1\0\2\3\1\0\2\3"+
    "\35\0\11\3\1\225\12\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\10\1\14\11\1\1\4\11"+
    "\15\1\1\0\1\1\5\0\4\11\31\1\2\11\1\0"+
    "\23\1\1\0\20\1\1\0\36\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol current = null;
    private Symbol sym(String token) {
        System.out.println(token);
        return new Symbol(token);
    }

    private Symbol sym(String token, String val) {
        System.out.println(token);
        return new Symbol(token, val);
    }

    public int line_number(){
        return yyline;
    }

    public Symbol get_current(){
        return current;
    }

    public String read_token() throws Exception{
        current = yylex();
        return current.getToken();
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return sym("$");
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <" + yytext() + "> at line " + yyline);
            } 
            // fall through
          case 55: break;
          case 2: 
            { return sym("id", yytext());
            } 
            // fall through
          case 56: break;
          case 3: 
            { return sym("int_const", yytext());
            } 
            // fall through
          case 57: break;
          case 4: 
            { /* do nothing */
            } 
            // fall through
          case 58: break;
          case 5: 
            { return sym("minus");
            } 
            // fall through
          case 59: break;
          case 6: 
            { return sym("divide");
            } 
            // fall through
          case 60: break;
          case 7: 
            { return sym("less");
            } 
            // fall through
          case 61: break;
          case 8: 
            { return sym("greater");
            } 
            // fall through
          case 62: break;
          case 9: 
            { return sym("lbrace");
            } 
            // fall through
          case 63: break;
          case 10: 
            { return sym("rbrace");
            } 
            // fall through
          case 64: break;
          case 11: 
            { return sym("lparen");
            } 
            // fall through
          case 65: break;
          case 12: 
            { return sym("rparen");
            } 
            // fall through
          case 66: break;
          case 13: 
            { return sym("lbracket");
            } 
            // fall through
          case 67: break;
          case 14: 
            { return sym("rbracket");
            } 
            // fall through
          case 68: break;
          case 15: 
            { return sym("semicolon");
            } 
            // fall through
          case 69: break;
          case 16: 
            { return sym("comma");
            } 
            // fall through
          case 70: break;
          case 17: 
            { return sym("plus");
            } 
            // fall through
          case 71: break;
          case 18: 
            { return sym("multiply");
            } 
            // fall through
          case 72: break;
          case 19: 
            { return sym("mod");
            } 
            // fall through
          case 73: break;
          case 20: 
            { return sym("equal");
            } 
            // fall through
          case 74: break;
          case 21: 
            { return sym("colon");
            } 
            // fall through
          case 75: break;
          case 22: 
            { return sym("bitwise_or");
            } 
            // fall through
          case 76: break;
          case 23: 
            { return sym("exclusive_add");
            } 
            // fall through
          case 77: break;
          case 24: 
            { return sym("bitwise_and");
            } 
            // fall through
          case 78: break;
          case 25: 
            { return sym("not");
            } 
            // fall through
          case 79: break;
          case 26: 
            { return sym("neq");
            } 
            // fall through
          case 80: break;
          case 27: 
            { return sym("leq");
            } 
            // fall through
          case 81: break;
          case 28: 
            { return sym("geq");
            } 
            // fall through
          case 82: break;
          case 29: 
            { return sym("assign");
            } 
            // fall through
          case 83: break;
          case 30: 
            { return sym("do");
            } 
            // fall through
          case 84: break;
          case 31: 
            { return sym("or");
            } 
            // fall through
          case 85: break;
          case 32: 
            { return sym("of");
            } 
            // fall through
          case 86: break;
          case 33: 
            { return sym("if");
            } 
            // fall through
          case 87: break;
          case 34: 
            { return sym("real_const", yytext());
            } 
            // fall through
          case 88: break;
          case 35: 
            { return sym("var");
            } 
            // fall through
          case 89: break;
          case 36: 
            { return sym("char_const", Character.toString(yytext().charAt(1)));
            } 
            // fall through
          case 90: break;
          case 37: 
            { return sym("string_const", yytext());
            } 
            // fall through
          case 91: break;
          case 38: 
            { return sym("and");
            } 
            // fall through
          case 92: break;
          case 39: 
            { return sym("end");
            } 
            // fall through
          case 93: break;
          case 40: 
            { return sym("real");
            } 
            // fall through
          case 94: break;
          case 41: 
            { return sym("char");
            } 
            // fall through
          case 95: break;
          case 42: 
            { return sym("bool_const", yytext());
            } 
            // fall through
          case 96: break;
          case 43: 
            { return sym("else");
            } 
            // fall through
          case 97: break;
          case 44: 
            { return sym("array");
            } 
            // fall through
          case 98: break;
          case 45: 
            { return sym("break");
            } 
            // fall through
          case 99: break;
          case 46: 
            { return sym("begin");
            } 
            // fall through
          case 100: break;
          case 47: 
            { return sym("while");
            } 
            // fall through
          case 101: break;
          case 48: 
            { return sym("return");
            } 
            // fall through
          case 102: break;
          case 49: 
            { return sym("string");
            } 
            // fall through
          case 103: break;
          case 50: 
            { return sym("integer");
            } 
            // fall through
          case 104: break;
          case 51: 
            { return sym("boolean");
            } 
            // fall through
          case 105: break;
          case 52: 
            { return sym("continue");
            } 
            // fall through
          case 106: break;
          case 53: 
            { return sym("function");
            } 
            // fall through
          case 107: break;
          case 54: 
            { return sym("procedure");
            } 
            // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
